### ISSUE TITLE
[design]회원가입 퍼블리싱

### ISSUE THREAD

**Issue by goldapple-ce** [S-V-23-BootCamp-Team-F/frontend#9]
## ✨ 구현 할 기능

기능에 대해 간략하게 설명해주세요!
회원가입 퍼블리싱
## 📢 구현 방식

기능을 구현할 방식에 대해 설명해주세요.

<br>

**Comment by jiyoon0701** [comment]
회원가입 퍼블리싱 design/#10 브랜치에 병합 후 작업할 계획이라 이슈 닫겠습니다!
